/**
 * NativeCN default theme preset for tailwindcss
 * Generated by NativeCN CLI
 */

module.exports = {
  theme: {
    extend: {
      colors: {
        // Light theme colors
        background: '#ffffff',
        foreground: '#252525',
        card: '#ffffff',
        'card-foreground': '#252525',
        popover: '#ffffff',
        'popover-foreground': '#252525',
        primary: '#343434',
        'primary-foreground': '#fbfbfb',
        secondary: '#f7f7f7',
        'secondary-foreground': '#343434',
        muted: '#f7f7f7',
        'muted-foreground': '#8d8d8d',
        accent: '#f7f7f7',
        'accent-foreground': '#343434',
        destructive: '#e13636',
        'destructive-foreground': '#e13636',
        border: '#ebebeb',
        input: '#ebebeb',
        ring: '#b4b4b4',

        // Dark mode colors (BDN Theme)
        dark: {
          background: '#232323',
          foreground: '#ffffff',
          card: '#474747',
          'card-foreground': '#ffffff',
          popover: '#474747',
          'popover-foreground': '#ffffff',
          primary: '#ffffff',
          'primary-foreground': '#232323',
          secondary: '#474747',
          'secondary-foreground': '#ffffff',
          muted: '#474747',
          'muted-foreground': 'rgba(255, 255, 255, 0.7)',
          accent: '#ba9988',
          'accent-foreground': '#ffffff',
          destructive: '#e13636',
          'destructive-foreground': '#ffffff',
          border: '#474747',
          input: '#474747',
          ring: '#ba9988',
        },

        // Sidebar colors
        sidebar: {
          DEFAULT: '#fbfbfb',
          foreground: '#252525',
          primary: '#343434',
          'primary-foreground': '#fbfbfb',
          accent: '#f7f7f7',
          'accent-foreground': '#343434',
          border: '#ebebeb',
          ring: '#b4b4b4',
        },

        'sidebar-dark': {
          DEFAULT: '#343434',
          foreground: '#fbfbfb',
          primary: '#5e46ff',
          'primary-foreground': '#fbfbfb',
          accent: '#444444',
          'accent-foreground': '#fbfbfb',
          border: '#444444',
          ring: '#707070',
        },
      },
      borderRadius: {
        xl: 16,
        lg: 10,
        md: 8,
        sm: 6,
      },
    },
  },
};
